[package]
name = "observable-cafe"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
chrono = "0.4"
dioxus = "0.7"

[target.'cfg(target_arch = "wasm32")'.dependencies]
futures-timer = { version = "3", features = ["wasm-bindgen"] }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
futures-timer = "3"

[features]
default = ["web"]
web = ["dioxus/web"]
